baseURL = "https://oldmill1.github.io/makemoneywithai/"
languageCode = "en-us"
title = "Make Money with AI"
theme = "gokarna"

[params]
  description = "Learn from the master.... Max Levy"
  author = "Max Levy"
  
[outputs]
  home = ["HTML"]
