baseURL = "https://oldmill1.github.io/makemoneywithai/"
languageCode = "en-us"
title = "Make Money with AI"
theme = "gokarna"
enableEmoji = true
defaultContentLanguage = "en"

[params]
  description = "Learn from the master.... Max Levy"
  author = "Max Levy"
  avatarSize = "size-m"
  footer = "Max Levy"
  showBackToTopButton = true

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
